#!/bin/bash

cd /sdcard/Download

curl -OL https://github.com/GabiAle97/mobox-updater/releases/download/mesa/mediafoundation.zip

unzip mediafoundation.zip -d mediafoundation

cd mediafoundation

export container_list=$(ls /data/user/0/com.antutu.ABenchMark/files/usr/wineprefix | tr '\n' ' ')
for container in $container_list; do 
    cp -r sys* /data/user/0/com.antutu.ABenchMark/files/usr/wineprefix/$container/drive_c/windows
done

if [ -f /data/user/0/com.antutu.ABenchMark/files/usr/wineprefix/drive_c/windows/system32/cmd.exe ]; then
    echo "CMD patched successfully! Now run the container, go to D:/mediafoundation and run \"install.bat\" to finish the installer"
else
    echo "Something failed. Check the logs and report it in my github, please!"
fi