#!/bin/bash

apt update -y
apt install -y glibc-repo
apt install -y mangohud-glibc
apt install -y libxcb*
apt install -y xorgproto*
apt install -y unzip

if [ ! -e backups ]; then
        mkdir backups
        cp $PREFIX/etc/termux-login.sh ~/backups
        cp $PREFIX/glibc/opt/libs/d3d/vkd3d.7z ~/backups
        cp $PREFIX/glibc/opt/libs/mesa/turnip-v6.5.7z ~/backups
        cp $PREFIX/glibc/opt/libs/d3d/dxvk-dev.7z ~/backups
        cp $PREFIX/glibc/bin/box64 ~/backups
        mv $PREFIX/glibc/wine-9.3-vanilla-wow64 ~/backups/wine-9.3-vanilla-wow64
fi

echo "export MANGOHUD=1" >> $PREFIX/etc/termux-login.sh
echo "export MANGOHUD_CONFIG=engine_version,ram,vulkan_driver" >> $PREFIX/etc/termux-login.sh
if [ $(su -c id -u &>/dev/null) ]; then 
        echo "su -c setenforce 0 &>/dev/null" >> $PREFIX/etc/termux-login.sh
fi
echo "export BOX64_IGNOREINT3=0" >> $PREFIX/etc/termux-login.sh
echo "export BOX64_FUTEX_WAITV=1" >> $PREFIX/etc/termux-login.sh
echo "export BOX64_DYNAREC_DIV0=0" >> $PREFIX/etc/termux-login.sh
echo "export BOX64_CEFDISABLEGPUCOMPOSITOR=0" >> $PREFIX/etc/termux-login.sh
echo "export BOX64_CEFDISABLEGPU=0" >> $PREFIX/etc/termux-login.sh
echo "export BOX64_MALLOC_HACK=0" >> $PREFIX/etc/termux-login.sh
echo "export BOX64_RESERVE_HIGH=0" >> $PREFIX/etc/termux-login.sh
echo "export BOX64_SSE_FLUSHTO0=" >> $PREFIX/etc/termux-login.sh
echo "export BOX64_SYNC_ROUNDING=1" >> $PREFIX/etc/termux-login.sh
echo "export BOX64_DYNAREC_WAIT=0" >> $PREFIX/etc/termux-login.sh
echo "export BOX64_X87_NO80BITS=0" >> $PREFIX/etc/termux-login.sh

wget https://github.com/HansKristian-Work/vkd3d-proton/releases/download/v2.12/vkd3d-proton-2.12.tar.zst -O vkd3d.tar.zst
tar xf vkd3d.tar.zst
cd vkd3d-proton-2.12/
mv x64 system32
mv x86 syswow64
7z a vkd3d.7z sys*
cp vkd3d.7z $PREFIX/glibc/opt/libs/d3d/vkd3d.7z

wget https://github.com/GabiAle97/mobox-updater/releases/download/mesa/mesa-24.1.0-clang-airidosas.7z -O turnip-v6.5.7z
cp turnip-v6.5.7z $PREFIX/glibc/opt/libs/mesa/turnip-v6.5.7z

wget https://github.com/doitsujin/dxvk/releases/download/v2.3.1/dxvk-2.3.1.tar.gz -O dxvk-dev.tar.gz
tar xf dxvk-dev.tar.gz
cd dxvk-2.3.1
mv x64 system32
mv x32 syswow64
7z a dxvk-dev.7z sys*
cp dxvk-dev.7z $PREFIX/glibc/opt/libs/d3d/dxvk-dev.7z

wget https://github.com/GabiAle97/mobox-updater/releases/download/mesa/box64-100524 -O box64
mv box64 $PREFIX/glibc/bin/box64

wget https://github.com/GabiAle97/mobox-updater/releases/download/mesa/wine-9.8-glibc-staging-wow64.tar.xz -O wine.tar.xz
mkdir wine
tar xf wine.tar.xz -C wine
mv wine/* wine/wine-9.3-vanilla-wow64
mv wine/wine-9.3-vanilla-wow64 $PREFIX/glibc/wine-9.3-vanilla-wow64

cd
rm -rf vkd3d.tar.zst vkd3d-proton-2.12

function undo_updater_changes(){
        cd ~/backups
        cp ~/backups/termux-login.sh $PREFIX/etc/termux-login.sh
        cp ~/backups/vkd3d.7z $PREFIX/glibc/opt/libs/d3d/vkd3d.7z
        cp ~/backups/turnip-v6.5.7z $PREFIX/glibc/opt/libs/mesa/turnip-v6.5.7z
        cp ~/backups/dxvk-dev.7z $PREFIX/glibc/opt/libs/d3d/dxvk-dev.7z
        cp ~/backups/box64 $PREFIX/glibc/bin/box64
        rm -rf $PREFIX/glibc/wine-9.3-vanilla-wow64
        mv ~/backups/wine-9.3-vanilla-wow64 $PREFIX/glibc/wine-9.3-vanilla-wow64
        

}

if [ ! -f storage/downloads/already-seen ]; then
        clear
        echo -e "Hola! Soy EmuTesting, o GabiAle97, como prefieras \xF0\x9F\x98\x80"
        sleep 4
        echo "Soy el creador de este script..."
        sleep 4
        echo "Esto es sumamente EXPERIMENTAL, y si algo sale mal..."
        sleep 4
        echo -e "Es posible que tengas que eliminar todos los datos de termux \xF0\x9F\x98\xA2"
        sleep 4
        echo "..."
        sleep 2
        echo "..."
        sleep 2
        echo -e "\U1F923 Debiste ver tu cara! \U1F923"
        sleep 4
        echo "Si es experimental, por supuesto"
        sleep 4
        echo -e "Peeeero hice un backup con los archivos originales para que puedas restaurarlos \xF0\x9F\x98\x80"
        sleep 4
        echo -e "Corriendo \e[1mundo_updater_changes\e[0m debería volver todo a la normalidad"
        sleep 4
        echo -e "De todos modos, puedes avisarme en https://github.com/GabiAle97/mobox-updater/issues para que pueda tomar acciones \xF0\x9F\x98\x80"
        sleep 4
        echo -e "Ahora deberías salir de termux con \e[1mexit\e[0m y volver a entrar para que las variables se carguen" 
        sleep 4
        echo -e "Me despido! Pero antes, te propongo un trato..." 
        sleep 4
        echo -e "Si este script hace que tus juegos funcionen mejor, ve a https://youtube.com/@EmuTesting?si=-PW83qSOo2b_VFZH y hazmelo saber suscribiendote \U1F911"
        sleep 4
        echo -e "De hecho, tengo un video jugando a Resident Evil Village usando este script, claro. Si quieres verlo, está acá: https://youtu.be/ZzCHjD8ZwOY"
        sleep 4
        echo -e "Eso es todo! Adios! \U1FAE1"
        touch storage/downloads/already-seen
        sleep 4
        echo -e "Este mensaje se autodestruirá! CORRE! \U1F4A3"
fi

